### ISSUE TITLE
E254: Cannot allocate color error in vim

### ISSUE THREAD

**Issue by ghost** [altercation/solarized#60]
Everything works fine in MacVim but when I launch vim in OSX terminal I get a whole lot of `E254: Cannot allocate color` errors. In my `.vimrc` I have this: `let g:solarized_termcolors=16` before  `colorscheme solarized`, after all the errors vim says to `Press ENTER or type command to continue` if I do that vim launches with white on black.

**Comment by mirageglobe** [comment]
@kzsh Thanks! thats the same problem i was having... it didnt recognise guibg=234 terminal 256 representation. changing it to the hex colour code works fine. cheers! 

as a ref... http://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html

**Comment by endingman** [comment]
which file change? @mirageglobe

**Comment by Will-Sommers** [comment]
I ended up having this issue when trying fixes relating to `$VIMRUNTIME` after upgrading vim via homebrew. I'm not sure if this is related but perhaps.

**Comment by bennypowers** [comment]
I had @Will-Sommers same issue. I made two changes to solve the problem

1. I changed `$VIMRUNTIME` from `/usr/share/bin/vim/vim80` to `/usr/local/share/vim/vim80/`
1. I changed `editor` in `~/.gitconfig` from `/usr/bin/vim` to `vim` (this solved a related problem - powerline errors when git ran vim)

Hope this comment is helpful. 👋

**Comment by pdxrod** [comment]
OS/X version 10.13.3. I made an error in my .vimrc file, didn't make a backup, and got into a huge mess. Tried everything suggested by googling "E254: Cannot allocate color error in vim". brew install vim, install MacVim, use mvim, etc.. Nothing worked. So I reinstalled from source, changed the references to vim in my .bash_profile to say /usr/local/share instead of /usr/share, and it worked a treat. How to install vim from source: https://blog.danny-willems.be/configure-install-vim-source/
