### ISSUE TITLE
In OS X Terminal.app, cursor is same color as input text

### ISSUE THREAD

**Issue by agos** [altercation/solarized#82]
This is a problem since by default the cursor is a block, so if I place the cursor on a character I can't see it.

**Comment by jacwah** [comment]
This is my top search result for "terminal.app block cursor color" which I googled after having the same issue as others in this thread. Because I prefer the block cursor, I came up with a solution -- set the opacity of the cursor to 50% (or other reasonable value). This actually looks nice and reading what is under the cursor is easy.

<img width="215" alt="screen shot 2017-07-23 at 16 07 51" src="https://user-images.githubusercontent.com/3816754/28499964-45dc3e62-6fc1-11e7-96bb-8210cecb6e96.png">
<img width="397" alt="screen shot 2017-07-23 at 16 08 53" src="https://user-images.githubusercontent.com/3816754/28499966-4c64c024-6fc1-11e7-9f3a-8e55714f390c.png">
